name: Compile for macOS

on:
  push:
    branches:
      - main  # Se ejecuta al hacer push a la rama main

jobs:
  build:
    runs-on: macos-latest  # Usa un runner de macOS

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Descarga tu código del repositorio

      - name: Compile for macOS
        run: |
          # Compila el código con clang (compilador de macOS)
          clang mike_macos.c -o mike_macos

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: mike_macos-executable
          path: mike_macos  # Sube el ejecutable como artefacto
